// Generated by CoffeeScript 1.4.0
(function() {
  var formidable, fs, qs, show, start, upload;

  qs = require("querystring");

  fs = require("fs");

  formidable = require("formidable");

  start = function(response) {
    var body;
    console.log("Request handler 'start' was called");
    body = "<!doctype html>\n<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html\" charset=UTF-8 />\n</head>\n<body>\n<form action=\"/upload\" enctype=\"multipart/form-data\" method=\"post\">\n<input type=\"file\" name=\"upload\">\n<input type=\"submit\" value=\"Upload\" />\n</form>\n</body>\n</html>";
    response.writeHead(200, {
      "Content-Type": "text/html"
    });
    response.write(body);
    return response.end();
  };

  upload = function(response, request) {
    var form;
    console.log("Request handler 'upload' was called");
    form = new formidable.IncomingForm();
    console.log("about to parse");
    form.parse(request, function(error, fields, files) {
      console.log("parsing done");
      return fs.rename(files.upload.path, "./tmp/test.png", function(err) {
        if (err) {
          fs.unlink("./tmp/test.png");
          return fs.rename(files.upload.path, "./tmp/test.png");
        }
      });
    });
    response.writeHead(200, {
      "Content-Type": "text/html"
    });
    response.write("received image: <br/> <img src='/show' />");
    return response.end();
  };

  show = function(response) {
    console.log("Request handler 'show' was called.");
    return fs.readFile("./tmp/test.png", "binary", function(error, file) {
      if (error) {
        response.writeHead(500, {
          "Content-Type": "text/plain"
        });
        response.write("WTF" + error + " \n");
        return response.end();
      } else {
        response.writeHead(200, {
          "Content-Type": 'image/png'
        });
        response.write(file, "binary");
        return response.end();
      }
    });
  };

  exports.start = start;

  exports.upload = upload;

  exports.show = show;

}).call(this);
